public class ProgramFlag{
		public static void main(String arguments[]){

			String RESET = "\u001B[0m"; // Команда сброса к параметрам по умолчанию

			String RED = "\u001B[38;2;255;0;0m";
			String GREEN = "\u001B[38;2;0;255;0m";
			String WHITE = "\u001B[38;2;255;255;255m";
			String BLUE = "\u001B[38;2;0;0;255m";
			String BLACK_YELLOW = "\u001B[38;2;200;200;35m";

			String ESC = "\u001B[38;2;R;G;Bm"; // Случайный цвет
			String RECTANGLE = "\u2588"; //0xDB

			System.out.println("");
			System.out.println("Италия");
			System.out.println("");
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(GREEN + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + WHITE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RESET);

			System.out.println("Молдова");
			System.out.println("");
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RED + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLACK_YELLOW + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + BLUE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE + RECTANGLE);
			System.out.println(RESET);

		}
}